In [81]:
my_list = [1,2,3]

In [82]:
import numpy as np

In [83]:
np.array(my_list)

array([1, 2, 3])

In [84]:
arr = np.array(my_list)

In [85]:
arr

array([1, 2, 3])

In [86]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [87]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [90]:
np.zeros(3)

array([0., 0., 0.])

In [91]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [93]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [94]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [95]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.random.rand(5)

array([0.65192743, 0.43004769, 0.43469451, 0.02609893, 0.42617141])

In [97]:
np.random.rand(5,5)

array([[7.21930517e-01, 7.96589217e-01, 8.24048146e-01, 1.71133583e-05,
        8.39916778e-01],
       [1.43610771e-01, 7.61506227e-01, 8.97159146e-01, 9.58373559e-01,
        1.78200446e-01],
       [8.55690979e-01, 4.89042604e-01, 4.98442833e-01, 5.61127717e-01,
        1.92027784e-01],
       [9.35250917e-01, 8.34293212e-02, 2.53198947e-01, 2.40177822e-01,
        2.21006360e-01],
       [2.07541962e-01, 3.69772778e-01, 8.24190722e-01, 5.85879472e-01,
        4.64708747e-01]])

In [98]:
np.random.rand(2)

array([0.85706028, 0.85348686])

In [99]:
np.random.rand(4,4)

array([[0.0544891 , 0.44853375, 0.90903583, 0.94595892],
       [0.33422401, 0.11546488, 0.81489365, 0.36438156],
       [0.49155211, 0.29548788, 0.66403716, 0.29692363],
       [0.55824426, 0.24764375, 0.95845798, 0.13009375]])

In [100]:
np.random.randint(1,100)

13

In [101]:
np.random.randint(1,100,10)

array([60, 40, 13, 12,  7, 89,  1, 76, 98, 24])

In [102]:
arr = np.arange(25)

In [103]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [104]:
ranarr = np.random.randint(0,50,10)

In [105]:
ranarr

array([39,  5, 42, 15,  5, 25, 25, 28, 12, 35])

In [121]:
np.random.randint(0,50,10)

array([35, 11, 40, 11, 11, 42, 16, 10,  1,  0])

In [122]:
arr = np.arange(25)

In [123]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [124]:
ranarr

array([39,  5, 42, 15,  5, 25, 25, 28, 12, 35])

In [125]:
ranarr.max()

42

In [126]:
ranarr.min()

5

In [127]:
ranarr.argmax()

2

In [128]:
ranarr.argmin()

1

In [129]:
arr.shape

(25,)

In [130]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
arr = arr.reshape(5,5)

In [132]:
arr.shape

(5, 5)

In [170]:
arr.dtype

dtype('int32')

In [171]:
from numpy.random import randint

In [172]:
randint(2,10) # 2 ile 10 arasinda random bir digit getir.

7

In [173]:
np.linspace(0,40,5) # 0 ile 50 arasinda linspace size=5 deger getir.

array([ 0., 10., 20., 30., 40.])

In [336]:
import numpy as np
np.random.randint(1,10)

1

In [337]:
import numpy as np

In [338]:
arr = np.arange(0,11) # 0 dan 10 a kadar bir array arange et.

In [339]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [212]:
arr[8]

8

In [213]:
arr[1:5]

array([1, 2, 3, 4])

In [214]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [215]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [216]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [217]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [218]:
arr[0:5] = 100

In [219]:
arr 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [220]:
arr = np.arange(0,11)

In [221]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [224]:
slice_of_arr = arr[0:6]

In [225]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [227]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [228]:
slice_of_arr[:] = 99

In [231]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [232]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [233]:
arr_copy = arr.copy()

In [234]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [235]:
arr_copy[:]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [236]:
arr_copy[:] = 100

In [237]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [238]:
arr # ilk arr in etkilenmemesi icin degisimden bir copy_arr olusturuyoruz.
# Degisiklikleri burda yapiyoruz ilk arr ayni kaliyor.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [246]:
import numpy as np

In [247]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [248]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [249]:
arr_2d[0][0]

5

In [250]:
arr_2d[0]

array([ 5, 10, 15])

In [251]:
arr_2d[1][1]

25

In [253]:
arr_2d[2,1]

40

In [254]:
arr_2d[2][1]

40

In [255]:
arr_2d[1,2]

30

In [257]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [256]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [258]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [263]:
arr  = np.arange(1,11)

In [264]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [265]:
arr > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [266]:
bool_arr = arr >5

In [267]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [268]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [269]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [270]:
arr[arr<3]

array([1, 2])

In [275]:
import numpy as np

In [277]:
arr_2d = np.arange(50).reshape(5,10)

In [278]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [280]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [279]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [283]:
import numpy as np
arr = np.arange(0,11)

In [284]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [282]:
arr[2:5]

array([2, 3, 4])

In [285]:
import numpy as np
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [286]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [287]:
arr_2d[0,2]

15

### NumPy Operations
Array with Array
Array with Scalars
Universal Array Functions

In [288]:
import numpy as np

In [289]:
arr = np.arange(0,11)

In [290]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [291]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [292]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [293]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [294]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [295]:
arr -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [296]:
arr / arr

C:\Users\ilkca\anaconda3\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [297]:
1/0

ZeroDivisionError: division by zero

In [298]:
1/arr

C:\Users\ilkca\anaconda3\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [299]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [300]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [301]:
np.exp(arr) #explotion unu aliyor sayilarin.

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [302]:
np.max(arr)

10

In [304]:
arr.max()

10

In [305]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [306]:
np.log(arr)

C:\Users\ilkca\anaconda3\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [307]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [308]:
import numpy as np
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])

In [309]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [310]:
 arr_2d[2,1]

40

In [311]:
arr_2d[:1,1:]

array([[10, 15]])

In [312]:
import numpy as np
arr = np.arange(1,6)
arr[arr>3]

array([4, 5])

In [313]:
import numpy as np
arr_1 = np.arange(0,10)
arr_2 = arr_1 * 3
np.max(arr_2)

27

In [314]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-arr_2

array([0., 0., 0., 0., 0.])

In [325]:
import numpy as np
arr=np.arange(1,37)
arr.shape

(36,)

# Exercises

In [326]:
import numpy as np

In [327]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [328]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [340]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [341]:
np.zeros(10) +5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [331]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [332]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create 3x3 matrix with values from 0 to 8

In [343]:
np.arange(9).reshape(3,3)  # 0 ile 9 arasinda 3x3 bir matrix olusturuyor.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [333]:
arr = np.arange(0,9)

In [334]:
arr.reshape(3,3) # ayni islemler bu sekilde de oluyor.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [344]:
np.eye(3) # 0 ile bir matrix i ne eye diyoruz.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1.

In [348]:
np.random.rand(1) # random bir sayi istiyoruz 1 e kadar olan.

array([0.76567449])

Use NumPy to  generate an array of 25 random numbers sampled from a standard normal distribution.

In [349]:
np.random.randn(25) # from a standard normal distribution 25 sayi istiyoruz.

array([-1.05287473, -0.51994274,  1.17539154, -1.40666563,  1.40480024,
       -0.10173506, -1.73934981,  0.932471  ,  1.09249891, -1.55411684,
        0.25851864, -0.00691252, -0.08139729,  0.53250512, -1.18353911,
        1.44351938,  0.49625091,  0.81016708, -1.40884329,  0.93990634,
       -0.44587223, -2.10364023, -1.02457501,  2.1379004 , -0.1192461 ])

In [350]:
np.random.randn(25).shape

(25,)

In [351]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [352]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [353]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create an array of 20 linearly spaced points between 0 and 1.

In [354]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

##### NumPy Indexing and Selection

In [355]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [357]:
mat[2:,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [358]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [359]:
mat[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [361]:
mat[3,4]

20

In [362]:
mat[:3,1] #mat[0:3,1]

array([ 2,  7, 12])

In [363]:
mat[:3,1:2] #mat[0:3,1]

array([[ 2],
       [ 7],
       [12]])

In [365]:
mat[-1,0:5] 

array([21, 22, 23, 24, 25])

In [367]:
mat[4,:] 

array([21, 22, 23, 24, 25])

In [368]:
mat[3:5,:] 

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [369]:
np.sum(mat)

325

In [370]:
mat.sum()

325

In [371]:
np.std(mat)

7.211102550927978

In [6]:
import numpy as np

In [7]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])