___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# Series

The first main data type we will learn about for pandas is the Series data type. Let's import Pandas and explore the Series object.

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

Let's explore this concept through some examples:

In [30]:
import numpy as np
import pandas as pd

In [36]:
s = pd.Series(['p','q','r','s'], index = [1,2,3,4])
s.sort_index()

1    p
2    q
3    r
4    s
dtype: object

In [37]:
s.sort_index(inplace =True)
s

1    p
2    q
3    r
4    s
dtype: object

In [38]:
s.sort_index(ascending = False)

4    s
3    r
2    q
1    p
dtype: object

In [39]:
s = pd.Series(['p','q','r','s'], index = [1,2,3,np.nan])

s.sort_index(na_position = "first")

NaN    s
1.0    p
2.0    q
3.0    r
dtype: object

In [40]:
s.sort_values(na_position = 'first')

1.0    p
2.0    q
3.0    r
NaN    s
dtype: object

In [42]:
s.sort_values(ascending = False, inplace = True)

In [44]:
s = pd.Series(['t','r','s','p','q'])

In [45]:
s.sort_values #degerleri sort ediyor alfabetik

<bound method Series.sort_values of 0    t
1    r
2    s
3    p
4    q
dtype: object>

In [46]:
s = pd.Series(['dog', 'cow', 'dog', 'cat', 'dog',
               'lion'], name='animal')

###### https://www.w3resource.com/pandas/series/series-isin.php#:~:text=The%20isin()%20function%20is,passed%20sequence%20of%20values%20exactly.&text=The%20sequence%20of%20values%20to%20test.

In [47]:
s.isin(['cow', 'dog']) 

0     True
1     True
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

In [ ]:
#PANDAS METHODS ---->>>> sort_index, sort_ values,sort_isin

### Creating a Series

You can convert a list,numpy array, or dictionary to a Series:

In [5]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

** Using Lists**

In [6]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [9]:
ser = pd.Series(my_list)
ser

0    10
1    20
2    30
dtype: int64

In [10]:
ser.dtype

dtype('int64')

In [11]:
ser.size #size ni veriyor

3

In [12]:
ser.ndim #boyut 1 boyutlu bide 2 boyut yapiyoruz oda matrix.

1

In [13]:
ser.values

array([10, 20, 30], dtype=int64)

In [14]:
for i in ser.values:
    print(i)

10
20
30


In [15]:
[i for i in ser.values]

[10, 20, 30]

In [16]:
ser.head(3) #BAKKKKK ??????

0    10
1    20
2    30
dtype: int64

In [17]:
ser.tail(3)# BAKKKKK ?????

0    10
1    20
2    30
dtype: int64

In [18]:
string = 'clarusway'

In [19]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [20]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [21]:
pd.Series([i for i in string])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [22]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d= {'a':10,'b':20,'c':30}

In [23]:
pd.Series(data= my_list)

0    10
1    20
2    30
dtype: int64

In [24]:
pd.Series(data= my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [25]:
pd.Series(data = labels)

0    a
1    b
2    c
dtype: object

In [26]:
pd.Series([sum, print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [28]:
mix_data =  [1,'cat',True]

In [29]:
pd.Series(mix_data)

0       1
1     cat
2    True
dtype: object

In [30]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

Using NUmpy

In [31]:
arr

array([10, 20, 30])

In [32]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [34]:
labels = ['a','b','c']

In [35]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

In [36]:
d

{'a': 10, 'b': 20, 'c': 30}

In [37]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

** NumPy Arrays **

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

** Dictionary**

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

In [10]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [11]:
# Even functions (although unlikely that you will use this)
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

## Using an Index

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [49]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                                   

In [50]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [51]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

In [52]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [16]:
ser1['USA']

1

Operations are then also done based off of index:

In [17]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [ ]:
panser

In [ ]:
panser[0]

In [ ]:
panser[0:3]

In [53]:
ser1['USA': "USSR"]

USA        1
Germany    2
USSR       3
dtype: int64

### pandas_series[Index] pandas_series[indices, indices...]

In [54]:
panser = pd.Series([121,200,150,99], index = ['ali','veli','gul', 'nur'])

In [55]:
panser

ali     121
veli    200
gul     150
nur      99
dtype: int64

In [56]:
panser["ali"]

121

In [57]:
panser[['veli','nur']]#liste icerisinde index aninda getiriyor isim altindaki verileri.cift parantez

veli    200
nur      99
dtype: int64

In [58]:
panser[0:3]

ali     121
veli    200
gul     150
dtype: int64

### Several Selecting Attributes

In [59]:
panser.index

Index(['ali', 'veli', 'gul', 'nur'], dtype='object')

In [60]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [61]:
panser.items

<bound method Series.items of ali     121
veli    200
gul     150
nur      99
dtype: int64>

In [63]:
panser.keys

<bound method Series.keys of ali     121
veli    200
gul     150
nur      99
dtype: int64>

In [64]:
panser.items()

In [65]:
list(panser.items())

[('ali', 121), ('veli', 200), ('gul', 150), ('nur', 99)]

In [66]:
for index, value in panser.items():
    print (index, "-", value)

ali - 121
veli - 200
gul - 150
nur - 99


In [67]:
'mehmet' in panser

False

In [68]:
"ali" in panser

True

In [69]:
"gulnur" in panser

False

In [70]:
99 in panser.values

True

In [71]:
506 in panser.values

False

In [72]:
panser['veli'] = 571 #atama broudcasting yaptik veli= 571 oldu
panser

ali     121
veli    571
gul     150
nur      99
dtype: int64

In [73]:
panser> 130

ali     False
veli     True
gul      True
nur     False
dtype: bool

In [74]:
panser[panser>130]

veli    571
gul     150
dtype: int64

Let's stop here for now and move on to DataFrames, which will expand on the concept of Series!
# Great Job!