___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [48]:
import pandas as pd
import numpy as np

In [49]:
datam = [1,2,39,67,90]
datam

[1, 2, 39, 67, 90]

In [50]:
pd.DataFrame(datam, columns= ['column_name'])

column_name
0            1
1            2
2           39
3           67
4           90

In [51]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
pd.DataFrame(m,columns = ['var1','var2','var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [53]:
df = pd.DataFrame(data = m,columns = ['var1','var2','var3'])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [54]:
df.head(1) #ilk satir

var1  var2  var3
0     1     2     3

In [55]:
df.head(2)#ilk iki satir

var1  var2  var3
0     1     2     3
1     4     5     6

In [56]:
df.tail(1)# sondan bir satir aliyor

var1  var2  var3
2     7     8     9

In [57]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [58]:
for i in df.columns:
    print(i)

var1
var2
var3


In [131]:
df.columns = ['new1','new2','new3']

In [132]:
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [133]:
type(df)

pandas.core.frame.DataFrame

In [134]:
df.shape

(3, 3)

In [135]:
df.ndim

2

In [136]:
df.size

9

In [137]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
type(df.values)

numpy.ndarray

In [139]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [140]:
s1

array([7, 4, 8, 7, 6])

In [141]:
s2

array([9, 4, 2, 7, 7])

In [142]:
s3

array([7, 0, 4, 1, 8])

In [143]:
myDict = {'var1': s1, 'var2': s2, 'var3': s3}

In [144]:
df1 = pd.DataFrame(myDict)
df1

var1  var2  var3
0     7     9     7
1     4     4     0
2     8     2     4
3     7     7     1
4     6     7     8

In [145]:
#df1 = s1+s2+s3

In [146]:
#df1

In [147]:
pwd

'C:\\Users\\ilkca\\DATA_SCIENCE\\03_Data_ANALYSIS_w_PHTHON\\03-Python-for-Data-Analysis-Pandas\\NumPy'

In [148]:
#ornekcsv.csv

In [149]:
df3 = pd.read_csv('ornekcsv.csv', delimiter = ";")
df3

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [150]:
df3.head() #default u ilk 5 satirdir

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [151]:
df1

var1  var2  var3
0     7     9     7
1     4     4     0
2     8     2     4
3     7     7     1
4     6     7     8

In [152]:
df1[1:3]

var1  var2  var3
1     4     4     0
2     8     2     4

In [153]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [154]:
[i for i in df.index]

[0, 1, 2]

In [155]:
df1.index = ["a", "b", "c", "d", "e"]
df1

var1  var2  var3
a     7     9     7
b     4     4     0
c     8     2     4
d     7     7     1
e     6     7     8

In [156]:
df1['b':'d'] #string oldugunda index e son eleman da dahil olur numeric te oyle degil.

var1  var2  var3
b     4     4     0
c     8     2     4
d     7     7     1

In [157]:
'new2' in df

True

In [158]:
'ali' in df

False

In [159]:
from numpy.random import randn
np.random.seed(101)

In [160]:
df3= pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [161]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [162]:
df4 = pd.DataFrame(index='A B C D E'.split())
df4

Empty DataFrame
Columns: []
Index: [A, B, C, D, E]

In [163]:
#df3= pd.DataFrame(randn(5,4),'A B C D E'.split(),'W X Y Z'.split())

In [164]:
#pd.DataFrame(index='A B C D E'.split(), data =randn(5,4), columns='W X Y Z'.split())

In [165]:
df3['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [166]:
type(df3['W'])

pandas.core.series.Series

In [167]:
df3.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [168]:
df3['W'].values

array([ 2.70684984,  0.65111795, -2.01816824,  0.18869531,  0.19079432])

In [169]:
df3['W'].ndim

1

In [170]:
df3['W'].shape

(5,)

In [171]:
df3[['W']] #koseli iki parantez DataFrame dondurur.

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [172]:
istedigimsutunlar = ['W', 'Z']
Wz_df = df3[istedigimsutunlar]

In [173]:
Wz_df

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [174]:
df3[['W', 'Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [175]:
df3[['W']]

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [176]:
#df3['W']
df3.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [177]:
type(df3.W)

pandas.core.series.Series

In [178]:
Wz_df

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [179]:
#df['ad soyad']

In [180]:
df3['A': 'C']

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [181]:
df3['C': 'C']

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [182]:
df3.loc[["C"], ['W']] #df3.loc['B', 'Y']

W
C -2.018168

In [183]:
df3.iloc[[0, 1],[0,2]] ### iloc ta 0 ve 1 row   0 ve 2 Column indexleri

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [184]:
df> 0 

new1  new2  new3
0  True  True  True
1  True  True  True
2  True  True  True

In [185]:
booldf = df > 0 

In [186]:
booldf

new1  new2  new3
0  True  True  True
1  True  True  True
2  True  True  True

In [187]:
df[booldf]

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [188]:
df[df > 0]

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [204]:
df=df3
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [205]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [206]:
df['W'] >0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [207]:
# Pass a list of column names
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [208]:
df[df["W"]>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [209]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [210]:
df[df['Z'] < 0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [216]:
resultdf = df[df['W'] > 0 ]
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [212]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [213]:
 df[df['W'] > 0 ] ['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [214]:
 df[df['W'] > 0 ] ['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [215]:
df[df['W'] > 0 ] [['Y', 'X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [217]:
boolser = df['W'] > 0

In [218]:
result = df[boolser]

In [219]:
result

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [220]:
boolser = df['W'] > 0
result = df[boolser]
mycols = ['Y', 'X']
result [mycols]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [223]:
df[(df['W'] > 0) and (df['Y'] > 1)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [224]:
True and True

True

In [225]:
df[(df['W'] > 0) & (df['Y'] > 1)] #df3[(df3['W'] >0) & df3["Y"]]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [226]:
df3[(df3['W'] >0) & df3["Y"]]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [227]:
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [228]:
df[(df['W'] > 0) & (df['Y'] > 1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [229]:
df[(df['W'] > 0)  | (df['Y'] > 1)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [230]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [231]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [232]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [233]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame Columns are just Series

**Creating a new column:**

In [237]:
df['new'] = df['W'] + df['Y']

In [238]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [239]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

** Removing Columns**

In [240]:
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
# Not inplace unless specified!
df

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

** Selecting Rows**

In [242]:
df.loc['A']

W      2.706850
X      0.628133
Y      0.907969
Z      0.503826
new    3.614819
Name: A, dtype: float64

Or select based off of position instead of label 

In [243]:
df.iloc[2]

W     -2.018168
X      0.740122
Y      0.528813
Z     -0.589001
new   -1.489355
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [244]:
df.loc['B','Y']

-0.8480769834036315

In [245]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

In [ ]:
df>0

In [ ]:
df[df>0]

In [ ]:
df[df['W']>0]

In [ ]:
df[df['W']>0]['Y']

In [ ]:
df[df['W']>0][['Y','X']]

For two conditions you can use | and & with parenthesis:

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
df3

In [ ]:
# Reset to default 0,1...n index
df3.reset_index()

In [246]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [248]:
df3['States'] = newind
df3['States']

A    CA
B    NY
C    WY
D    OR
E    CO
Name: States, dtype: object

In [ ]:
df3

In [ ]:
df3.set_index('States')

In [ ]:
df

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [250]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [253]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [254]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [255]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [263]:
df.loc['G1'].loc[1]  # iloc[0]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [264]:
df.index.names

FrozenList([None, None])

In [265]:
df.index.names = ['Group','Num']

In [266]:
df

A         B
Group Num                    
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

In [267]:
df.xs('G1')

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [268]:
df.xs(['G1',1])

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [269]:
df.xs(1,level='Num')

A         B
Group                    
G1     0.302665  1.693723
G2     0.166905  0.184502

# Great Job!