## NumPy Indexing and Selection¶
In this lecture we will discuss how to select elements or groups of elements from an array.

In [ ]:
import numpy as np

In [212]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
np.random.randint(5,25,size = (2,4))

array([[16, 24, 22,  9],
       [19, 14,  5, 15]])

In [15]:
np.random.randint(1,[3,50,100])

array([ 1, 43, 83])

In [16]:
np.random.randint(1,[3,50])

array([ 2, 23])

In [17]:
np.random.randint(1,[3,50,100], size = (5,3)) # icerdeki liste sutunlarin ust sinirlarini belirler

array([[ 1, 49, 64],
       [ 1, 12, 94],
       [ 2, 20, 56],
       [ 2, 42, 42],
       [ 1, 46, 76]])

In [18]:
np.random.randint([3,30,70], 111)

array([ 36, 108,  90])

In [19]:
arr = np.arange (25)
ranarr = np.random.randint(0, 50,10)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr

array([33, 40,  3, 40, 26, 43, 17, 23, 15, 21])

# Reshape

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr.reshape(2,5)

array([[33, 40,  3, 40, 26],
       [43, 17, 23, 15, 21]])

# max,min,armax, argmin

In [27]:
ranarr

array([33, 40,  3, 40, 26, 43, 17, 23, 15, 21])

In [28]:
ranarr.max()

43

In [29]:
ranarr.min()

3

In [30]:
ranarr.argmax()

5

In [31]:
ranarr.argmin()

2

# Some other attributes   ndim, shape, size, dtypr

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.shape

(25,)

In [34]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [73]:
arr.reshape(25,1).shape

(25, 1)

# dtype

In [38]:
arr.dtype

dtype('int32')

In [39]:
a = np.random.randint(10, size = 10)

In [40]:
a.dtype

dtype('int32')

In [42]:
b = np.full((4,6), 2.2)
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [43]:
b.dtype

dtype('float64')

In [44]:
c = np.full((4,6), "2.2")
c

array([['2.2', '2.2', '2.2', '2.2', '2.2', '2.2'],
       ['2.2', '2.2', '2.2', '2.2', '2.2', '2.2'],
       ['2.2', '2.2', '2.2', '2.2', '2.2', '2.2'],
       ['2.2', '2.2', '2.2', '2.2', '2.2', '2.2']], dtype='<U3')

In [45]:
c.dtype

dtype('<U3')

In [46]:
a

array([2, 6, 6, 4, 0, 7, 7, 7, 2, 5])

In [47]:
a.ndim

1

In [48]:
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [49]:
b.ndim

2

# Size

In [50]:
a

array([2, 6, 6, 4, 0, 7, 7, 7, 2, 5])

In [51]:
a.size

10

In [52]:
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [53]:
b.size

24

In [54]:
x = np.array([1,2,3])
y = np.array([4,5,6])


In [55]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [56]:
z = np.array([7,8,9])

In [57]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2d matrix

In [61]:
a1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [63]:
a1 =np.concatenate([x,y]).reshape(2,3)

In [64]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a1 =np.concatenate([a1,a1])


In [66]:
a1 =np.concatenate([a1,a1], axis = 1)

# split 

In [67]:
x =np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [68]:
np.split(x,[3,5])  # ary[:3] ary [3:5] ary[5:] olusur.

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [69]:
a, b, c = np.split(x,[3,5])

In [70]:
a

array([1, 2, 3])

In [71]:
b

array([99, 99])

In [72]:
c

array([3, 2, 1])

In [76]:
np.split(x,4)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [ ]:
# 2

In [77]:
m = np.arange(20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [78]:
np.split(m,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [79]:
np.split(m,[1,3], axis= 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [80]:
np.vsplit(m,[1,3]) # vertical eksende bolunur. Dikey olarak bolme oldu.

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [81]:
np.vsplit(m,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [89]:
upper, lower = np.vsplit(m, [3])

In [90]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [133]:
m = np.arange(20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [85]:
np.vsplit(m,5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [92]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [94]:
np.hsplit(m,[2]) # iki array left and right uretir

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [96]:
left, right = np.hsplit(m, [2])

In [97]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [98]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

# Sorting of the Array

In [99]:
v= np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [100]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [102]:
v.sort() # changed implace
v

array([1, 2, 3, 4, 5])

# 2d Matrix

In [105]:
tw = np.random.randint(5,100,(3,3))
tw

array([[62, 24, 16],
       [22, 87, 26],
       [93, 58, 56]])

In [106]:
np.sort(tw, axis = 0) #sutun sutun (sutunlar kendi iceriside) siralama oldu sort axis=0 ile. 

array([[22, 24, 16],
       [62, 58, 26],
       [93, 87, 56]])

In [107]:
np.sort(tw, axis = 1) #satir satir (satir icinde) siralama oldu sort axis=1 ile. 

array([[16, 24, 62],
       [22, 26, 87],
       [56, 58, 93]])

In [109]:
arr  = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr[8]

8

In [111]:
arr[-1]

10

In [112]:
arr[1:5]

array([1, 2, 3, 4])

In [113]:
arr[0:5] # arr[start:stop:step]

array([0, 1, 2, 3, 4])

In [114]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [115]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

# Broadcasting

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [118]:
a = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [119]:
a[0:3] = 100

TypeError: can only assign an iterable

In [120]:
arr  = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [123]:
slice_of_arr [:] = 99

In [125]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [127]:
arr_copy[0:6] = [0,1,2,3,4,5]
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [130]:
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [132]:
np.linspace(0,10,num=50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [131]:
np.linspace(0,10) #num = 50 default 50 linspace in

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# Indexing a 2D array (matrices)

In [141]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [142]:
arr_2d[1]

array([20, 25, 30])

In [143]:
arr_2d[-1]

array([35, 40, 45])

In [144]:
arr_2d[1][0]

20

In [148]:
arr_2d[1,0]

20

In [149]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [150]:
arr_2d[2,:]

array([35, 40, 45])

In [151]:
arr_2d[-1]

array([35, 40, 45])

In [171]:
arr_2d[:,-1:]

array([[15],
       [30],
       [45]])

In [156]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [157]:
arr_2d[:,1]

array([10, 25, 40])

In [217]:
arr_2d[:,1:2]

array([[10],
       [55],
       [40]])

In [215]:
arr_2d[1,1] = 55

In [216]:
arr_2d

array([[ 3, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [213]:
arr_2d.dtype

dtype('int32')

In [219]:
arr_2d[0,0] = 32.3

In [220]:
arr_2d

array([[32, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

# Fancy Indexing

In [222]:
v = np.arange(0,30,3)

In [223]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [224]:
v[1]

3

In [225]:
v[5]

15

In [227]:
idx_list = [1,3,5] # v array ini indexleme yapiyoruz sirasiyla elemanlari cekiyoruz.

In [228]:
v[idx_list]

array([ 3,  9, 15])

In [232]:
arr2d = np.zeros((10,10), dtype = int)

In [233]:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [234]:
arr2d.shape

(10, 10)

In [246]:
arr_length = arr2d.shape[1]

In [251]:
arr_length

10

In [248]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [249]:
arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [250]:
for i in range (arr_length):
    arr2d[i] = i
    
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [253]:
arr2d[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [254]:
arr2d[[6,4,2,7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

# any_array[[row indices], [colum indices]]

In [255]:
jj = np.arange(1,17).reshape((4,4))
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [263]:
jj[[1,2], [0,3]] #######?????????????

array([ 5, 12])

In [257]:
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

In [258]:
jj[[1],[1,3]]

array([6, 8])

In [179]:
jj[[0,3],1]

array([ 2, 14])

# Using basic index and fancy index together¶

In [180]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [259]:
jj[1, [1,3]]

array([6, 8])

In [260]:
jj[[0, 3], 1]

array([ 2, 14])

In [183]:
jj[0:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [261]:
jj[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

In [262]:
jj[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

# More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection
Let's briefly go over how to use brackets for selection based off of comparison operators.



In [264]:
arr = np.arange(1,11)

In [265]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [266]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [267]:
bool_arr = arr > 4

In [268]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [269]:
arr[arr> 4 ]

array([ 5,  6,  7,  8,  9, 10])

In [271]:
arr[(arr != 3) & (arr !=4)] ##  &==>and | ==>or

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [272]:
# 3'e bölünen tek sayilar:
arr[(arr%3==0) &(arr%2!=0)]

array([3, 9])

# Aritmetic Operations

In [186]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [188]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [189]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [190]:
arr / arr

C:\Users\ilkca\anaconda3\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [273]:
1/ arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [274]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [279]:
v = np.array([1,2,3,4,5])  #arange(0,6) rangini de yazabilirdik ayni array icin.
v

array([1, 2, 3, 4, 5])

In [280]:
v-1

array([0, 1, 2, 3, 4])

In [281]:
v*5

array([ 5, 10, 15, 20, 25])

In [282]:
v * 5 / 10 - 1  # carpma, bolme, toplama, cikarma sirasi oluyor.

array([-0.5,  0. ,  0.5,  1. ,  1.5])

# Statistical Calculations

In [200]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
np.log10(10000) # Normalize etmek, baskilamak icin kullaniyoruz.

4.0

In [204]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [205]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [206]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [207]:
np.sin(np.pi/2)

1.0

In [208]:
np.tan(np.pi/4)

0.9999999999999999

np.mean(arr,axis=0) | Returns mean along specific axis

arr.sum() | Returns sum of arr

arr.min() | Returns minimum value of arr

arr.max(axis=0) | Returns maximum value of specific axis

np.var(arr) | Returns the variance of array

np.std(arr,axis=1) | Returns the standard deviation of specific axis

arr.corrcoef() | Returns correlation coefficient of array